# Cloud Foundry Java Buildpack
# Copyright 2013-2016 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configuration for JRE repositories keyed by vendor
# If Java 7 is required, permgen will be used instead of metaspace. Please see the documentation for more detail.
---
jre:
  version: 1.7.0_51
  repository_root: "{default.repository.root}/openjdk/{platform}/{architecture}"

  memory_sizes:
    
    permgen: 64m..

  memory_heuristics:
    heap: 65
 
    native: 15
    permgen: 10
    stack: 10
  memory_initials:
    heap: 100%
 
    permgen: 100%
